### **Type conversion methods within the same data types in Python:**



In [ ]:
#Integer:

#Float to Integer: int()

my_float = 3.14
converted_integer = int(my_float)
converted_integer

3

In [ ]:
#String to Integer: int()
my_string = "123"
converted_integer = int(my_string)
converted_integer

123

In [ ]:
#Float:

#Integer to Float: float()
my_integer = 5
converted_float = float(my_integer)
converted_float

5.0

In [ ]:
#String to Float: float()
my_string = "3.14"
converted_float = float(my_string)
converted_float

3.14

In [ ]:
#String:

#Integer to String: str()
my_integer = 42
converted_string = str(my_integer)
converted_string

'42'

In [ ]:
#Float to String: str()
my_float = 3.14
converted_string = str(my_float)
converted_string

'3.14'

In [ ]:
#Boolean:

#Integer to Boolean: bool()
my_integer = 0
converted_boolean = bool(my_integer)
converted_boolean

False

In [ ]:
#String to Boolean: bool()
my_string = "True"
converted_boolean = bool(my_string)
converted_boolean

True

For Practice:

Integer Conversion:

1.	Convert the float 3.14 to an integer.
2.	Convert the string "123" to an integer.
3.	Convert the boolean True to an integer.

Float Conversion:

4.	Convert the integer 5 to a float.
5.	Convert the string "3.14" to a float.
6.	Convert the boolean False to a float.

String Conversion:
7.	Convert the integer 42 to a string.
8.	Convert the float 3.14 to a string.
9.	Convert the boolean True to a string.

Boolean Conversion:
10.	Convert the integer 0 to a boolean.
11.	Convert the integer 42 to a boolean.
12.	Convert the string "True" to a boolean.

Mixed Conversion:
13.	Convert the integer 10 to a float, then back to an integer.
14.	Convert the float 2.5 to an integer, then back to a float.
15.	Convert the string "False" to a boolean, then back to a string.



### **Type conversion methods within different data structures in Python:**

In [ ]:
#List:

#Tuple to List: list()
my_tuple = (1, 2, 3)
converted_list = list(my_tuple)
converted_list

[1, 2, 3]

In [ ]:
#String to List: list()
my_string = "hello"
converted_list = list(my_string)
converted_list

['h', 'e', 'l', 'l', 'o']

In [ ]:
#Set to List: list()
my_set = {1, 2, 3}
converted_list = list(my_set)
converted_list

[1, 2, 3]

In [ ]:
#Tuple:

#List to Tuple: tuple()
my_list = [1, 2, 3]
converted_tuple = tuple(my_list)
converted_tuple

(1, 2, 3)

In [ ]:
#String to Tuple: tuple()
my_string = "hello"
converted_tuple = tuple(my_string)
converted_tuple

('h', 'e', 'l', 'l', 'o')

In [ ]:
#Set to Tuple: tuple()
my_set = {1, 2, 3}
converted_tuple = tuple(my_set)
converted_tuple

(1, 2, 3)

In [ ]:
#Set:

#List to Set: set()
my_list = [1, 2, 3]
converted_set = set(my_list)
converted_set

{1, 2, 3}

In [ ]:
#Tuple to Set: set()
my_tuple = (1, 2, 3)
converted_set = set(my_tuple)
converted_set

{1, 2, 3}

In [ ]:
#String to Set: set()
my_string = "hello"
converted_set = set(my_string)
converted_set

{'e', 'h', 'l', 'o'}

In [ ]:
 #String:

#List to String: join()
my_list = ["h", "e", "l", "l", "o"]
converted_string = "".join(my_list)
converted_string

'hello'

In [ ]:
#Tuple to String: join()
my_tuple = ("h", "e", "l", "l", "o")
converted_string = "".join(my_tuple)
converted_string

'hello'

In [ ]:
#Set to String: join()
my_set = {"h", "e", "l", "l", "o"}
converted_string = "".join(my_set)
converted_string

'lheo'

For Practice:

List Conversion:
1.	Convert a tuple (1, 2, 3) to a list.
2.	Convert a string "hello" to a list of characters.
3.	Convert a set {1, 2, 3} to a list.

Tuple Conversion:
4.	Convert a list [1, 2, 3] to a tuple.
5.	Convert a string "world" to a tuple of characters.
6.	Convert a set {4, 5, 6} to a tuple.

Set Conversion:
7.	Convert a list [1, 2, 3] to a set.
8.	Convert a tuple (7, 8, 9) to a set.
9.	Convert a string "python" to a set of characters.

String Conversion:
10.	Convert a list [1, 2, 3] to a string representation.
11.	Convert a tuple (4, 5, 6) to a string representation.
12.	Convert a set {7, 8, 9} to a string representation.

Mixed Conversions:
13.	Convert a list [1, 2, 3] to a tuple, then to a set, and finally back to a list.
14.	Convert a string "hello" to a list, then to a tuple, and finally back to a string.
15.	Convert a set {4, 5, 6} to a tuple, then to a list, and finally back to a set.

Nested Conversion:
16.	Convert a nested list [[1, 2], [3, 4], [5, 6]] to a list of tuples.
17.	Convert a nested tuple ((7, 8), (9, 10)) to a list of lists.

